AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  1-crud-http-api

Globals:
  Function:
    Timeout: 30
Resources:
  UserApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: "3.0.1"
        info:
          version: "1.0"
          title: "Dev-UserApi"
        paths:
          "/users":
            get:
              responses:
                "200":
                  description: "200 response"
            post:
              responses:
                "200":
                  description: "200 response"
          "/users/{id}":
            get:
              responses:
                "200":
                  description: "200 response"
            put:
              responses:
                "200":
                  description: "200 response"
            delete:
              responses:
                "200":
                  description: "200 response"
  UserCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.create
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        UserCreate:
          Type: HttpApi
          Properties:
            Path: /users
            Method: post
            ApiId: !Ref UserApi
  UserReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.read
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        UserRead:
          Type: HttpApi
          Properties:
            Path: /users
            Method: get
            ApiId: !Ref UserApi
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.delete
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        UserRead:
          Type: HttpApi
          Properties:
            Path: /users/{id}
            Method: delete
            ApiId: !Ref UserApi
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.update
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        UserRead:
          Type: HttpApi
          Properties:
            Path: /users/{id}
            Method: put
            ApiId: !Ref UserApi

Outputs:
  UserCreateFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UserCreateFunctionRole.Arn
  UserReadFunction:
    Description: "User read Lambda Function ARN"
    Value: !GetAtt UserReadFunction.Arn
  UserReadFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UserReadFunctionRole.Arn
