version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g8kuev6d7ak5"
s3_prefix = "Dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
